### PR TITLE
[compiler] Canonicalize power op with both operand being constant

### PR DESCRIPTION
**Pull request by Mi-Jiazhi**

### CODE REVIEW

**Comment by yaochengji** [comment]
The shape of the test seems too large. Could you use a smaller one instead?

**Comment by Mi-Jiazhi** [comment]
> The shape of the test seems too large. Could you use a smaller one instead?

sure, I will change that case shape right away

**Comment by yaochengji** [comment]
@Mi-Jiazhi could you sign the CLA?

**Review by yaochengji — APPROVED** [review]

**Comment by WillemJiang** [comment]
@Mi-Jiazhi Please sign the CLA when you have new PR need to submit.

**Pull request closed without merging**
